trigger:
  - main

pool:
  vmImage: ubuntu-latest

container: mcr.microsoft.com/azure-dev-cli-apps:latest

steps:
  - task: AzureCLI@2
    displayName: Azure Dev Provision
    inputs:
      azureSubscription: azconnection
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        azd deploy --no-prompt
        
        az group create --name MyResourceGroup --location eastus
        az appservice plan create --name MyPlan --resource-group MyResourceGroup --sku B1
        az webapp create --name MyWebApp --resource-group MyResourceGroup --plan MyPlan
    env:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
      AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
      STRIPE_PUBLIC_KEY: "stripubkey"
      STRIPE_SECRET_KEY: "strisecretkey"
      STRIPE_WEBHOOK_SECRET: "striwebhooksecret"

  - task: AzureCLI@2
    displayName: Azure Dev Deploy
    inputs:
      azureSubscription: azconnection
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        azd deploy --no-prompt
    env:
      AZURE_SUBSCRIPTION_ID: ${AZURE_SUBSCRIPTION_ID}
      AZURE_ENV_NAME: ${AZURE_ENV_NAME}
      AZURE_LOCATION: ${AZURE_LOCATION}
